In [1]:
import numpy as np

a=np.random.randn(5)

In [2]:
print(a)

[-0.71657271 -1.33493631 -0.54195424 -0.65712762 -0.21456912]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-0.71657271 -1.33493631 -0.54195424 -0.65712762 -0.21456912]


In [6]:
print(np.dot(a,a.T))

3.067102418406137


In [7]:
a=np.random.randn(5,1)
print(a)

[[-0.14333019]
 [ 0.1370092 ]
 [ 0.38770145]
 [ 0.30796777]
 [ 0.41782798]]


In [8]:
print(np.dot(a,a.T))

[[ 0.02054354 -0.01963755 -0.05556932 -0.04414108 -0.05988736]
 [-0.01963755  0.01877152  0.05311867  0.04219442  0.05724628]
 [-0.05556932  0.05311867  0.15031242  0.11939955  0.16199252]
 [-0.04414108  0.04219442  0.11939955  0.09484414  0.12867755]
 [-0.05988736  0.05724628  0.16199252  0.12867755  0.17458022]]


In [9]:
print(a.T)

[[-0.14333019  0.1370092   0.38770145  0.30796777  0.41782798]]


In [10]:
print(a.T.shape)

(1, 5)


In [11]:
assert(a.shape==(5,1))